language: go
go:
    - 1.7
    - 1.8
    - 1.9
install:
    - go get github.com/landonr/bruxism/carbonitexplugin
    - go get github.com/landonr/bruxism/chartplugin
    - go get github.com/landonr/bruxism/comicplugin
    - go get github.com/landonr/bruxism/discordavatarplugin
    - go get github.com/landonr/bruxism/emojiplugin
    - go get github.com/landonr/bruxism/inviteplugin
    - go get github.com/landonr/bruxism/liveplugin
    - go get github.com/landonr/bruxism/mtgplugin
    - go get github.com/landonr/bruxism/musicplugin
    - go get github.com/landonr/bruxism/mysonplugin
    - go get github.com/landonr/bruxism/numbertriviaplugin
    - go get github.com/landonr/bruxism/playedplugin
    - go get github.com/landonr/bruxism/playingplugin
    - go get github.com/landonr/bruxism/reminderplugin
    - go get github.com/landonr/bruxism/statsplugin
    - go get github.com/landonr/bruxism/streamerplugin
    - go get github.com/landonr/bruxism/topstreamersplugin
    - go get github.com/landonr/bruxism/triviaplugin
    - go get github.com/landonr/bruxism/youtubejoinplugin
    - go get github.com/landonr/bruxism
    - go get -v .
